---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-CheckOS
no_index:
  directory:
    - t
    - inc
requires:
  Data::Compare: 1.21
  File::Find::Rule: 0.28
  File::Temp: 0.19
  Test::More: 0.62
resources:
  bugtracker: https://github.com/DrHyde/perl-modules-Devel-CheckOS/issues/new
  repository: https://github.com/DrHyde/perl-modules-Devel-CheckOS
version: 1.73
