--- #YAML:1.0
name:                Devel-CheckOS
version:             1.3
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    File::Find::Rule:              0.28
    Test::More:                    0.62
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
