# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Devel-CheckOS
version:      1.44
version_from: lib/Devel/CheckOS.pm
installdirs:  site
requires:
    File::Find::Rule:              0.28
    File::Temp:                    0.2
    Test::More:                    0.62

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
